config/routes.rb
Pattana::Engine.routes.draw do

  get 'dashboard/pattana',  to: "dashboard#index",  as: :dashboard

  scope :admin do
    resources :countries,  as: :countries do
      member do
        get :regions
        get :cities
        get :show_in_api
        get :hide_in_api
        get :mark_as_operational
        get :remove_operational
      end
    end

    resources :regions,  as: :regions do
      member do
        get :cities
        get :show_in_api
        get :hide_in_api
        get :mark_as_operational
        get :remove_operational
      end
    end

    resources :cities,  as: :cities do
      member do
        get :show_in_api
        get :hide_in_api
        get :mark_as_operational
        get :remove_operational
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get 'countries', :controller => "countries", action: :index, as: :countries
      get ':country_id/regions', :controller => "regions", action: :index, as: :regions
      get 'countries/:country_id/cities', :controller => "cities", action: :cities_in_a_country, as: :cities_in_a_country
      get 'regions/:region_id/cities', :controller => "cities", action: :cities_in_a_region, as: :cities_in_a_region
    end
  end
  
  scope :docs, as: 'docs' do
    namespace :api do
      namespace :v1 do
        get 'countries', :controller => "docs"
        get 'regions', :controller => "docs"
        get 'cities_in_a_country', :controller => "docs"
        get 'cities_in_a_region', :controller => "docs"
      end
    end
  end

end

app/controllers/pattana/api/v1/base_controller.rb
module Pattana
  module Api
    module V1
      class BaseController < ActionController::API

        include ActionController::HttpAuthentication::Token::ControllerMethods
        include RenderApiHelper

      end
    end
  end
end

app/controllers/pattana/api/v1/cities_controller.rb
module Pattana
  module Api
    module V1
      class CitiesController < BaseController

        def cities_in_a_country
          proc_code = Proc.new do
            @country = Country.find_by_id(params[:country_id])
            if @country
              @relation = @country.cities.includes(:region, :country).show_in_api(true).order("cities.name ASC")
              @relation = @relation.search(params[:q]) if params[:q]
              @relation = @relation.operational(true) if params[:operational] && ["y","t","yes","true",1].include?(params[:operational].downcase)
              @cities = @relation.all
              @data = ActiveModelSerializers::SerializableResource.new(@cities, each_serializer: CityPreviewSerializer)
              @success = true
            else
              @success = false
              @errors = {
                heading: I18n.translate("api.cities.country_not_found.heading"),
                message: I18n.translate("api.cities.country_not_found.message")
              }
            end
          end
          render_json_response(proc_code)
        end

        def cities_in_a_region
          proc_code = Proc.new do
            @region = Region.find_by_id(params[:region_id])
            if @region
              @relation = @region.cities.includes(:region, :country).show_in_api(true).order("cities.name ASC")
              @relation = @relation.search(params[:q]) if params[:q]
              @relation = @relation.operational(true) if params[:operational] && ["y","t","yes","true",1].include?(params[:operational].downcase)
              @cities = @relation.all
              @data = ActiveModelSerializers::SerializableResource.new(@cities, each_serializer: CityPreviewSerializer)
              @success = true
            else
              @success = false
              @errors = {
                heading: I18n.translate("api.cities.region_not_found.heading"),
                message: I18n.translate("api.cities.region_not_found.message")
              }
            end
          end
          render_json_response(proc_code)
        end
      end
    end
  end
end

app/controllers/pattana/api/v1/countries_controller.rb
module Pattana
  module Api
    module V1
      class CountriesController < BaseController

        def index
          proc_code = Proc.new do
            @relation = Country.show_in_api(true).order("countries.name ASC")
            @relation = @relation.search(params[:q]) if params[:q]
            @relation = @relation.operational(true) if params[:operational] && ["y","t","yes","true",1].include?(params[:operational].downcase)
            @countries = @relation.all
            @data = ActiveModelSerializers::SerializableResource.new(@countries, each_serializer: CountryPreviewSerializer)
            @success = true
          end
          render_json_response(proc_code)
        end

        
        
      end
    end
  end
end

app/controllers/pattana/api/v1/docs_controller.rb
module Pattana
  module Api
    module V1
      class DocsController < Pattana::ApplicationController

        layout 'kuppayam/docs'

        before_action :set_nav_items, :set_tab_items
        helper_method :breadcrumb_home_path

        def countries
          set_title("Countries API")
          @request_type = "GET"
          @end_point = "/api/v1/countries"
          @description = <<-eos
          This API will return all the countries with other details like dialing prefix and ISO codes. <br>
          This API can also be used to search countries by passing a query parameter 'q'.<br>
          eos

          @info = "It will return only those countries who has show_in_api set true"

          @input_headers = {
            "Content-Type" => { value: "application/json", description: "The MIME media type for JSON text is application/json. This is to make sure that a valid json is returned. The default encoding is UTF-8. " }
          }

          @example_path = "pattana/api/v1/docs/"
          @examples = ["pos_case_1", "pos_case_2", "pos_case_3", "pos_case_4"]

          set_nav("docs/pattana/countries")

          render 'kuppayam/api/docs/show'
        end

        def regions
          set_title("Regions API")
          @request_type = "GET"
          @end_point = "/api/v1/:country_id/regions"
          @description = <<-eos
          This API will return all the regions in a particular country. <br>
          The Country ID has to be passed. <br>
          This API can also be used to search regions by passing a query parameter 'q'.
          eos

          @info = "It will return only those regions who has show_in_api set true"

          @input_headers = {
            "Content-Type" => { value: "application/json", description: "The MIME media type for JSON text is application/json. This is to make sure that a valid json is returned. The default encoding is UTF-8. " }
          }

          @input_params = {
            country_id: { mandatory: true, description: "The Country ID. You will get it from the Countries API", example: "for e.g: Country Id for U.A.E is 235 and that of India is 100", default: "" }
          }

          @example_path = "pattana/api/v1/docs/"
          @examples = ["pos_case_1", "pos_case_2", "pos_case_3", "pos_case_4", "neg_case_1"]

          set_nav("docs/pattana/regions")

          render 'kuppayam/api/docs/show'
        end

        def cities_in_a_country
          set_title("Cities API (in a country)")
          @request_type = "GET"
          @end_point = "/api/v1/countries/:country_id/cities"
          @description = ""
          @description = <<-eos
          This API will return all the cities in a particular country. <br>
          The Country ID has to be passed. <br>
          This API can also be used to search cities in a country by passing a query parameter 'q'.
          eos

          @info = "It will return only those cities who has show_in_api set true"

          @input_headers = {
            "Content-Type" => { value: "application/json", description: "The MIME media type for JSON text is application/json. This is to make sure that a valid json is returned. The default encoding is UTF-8. " }
          }

          @input_params = {
            country_id: { mandatory: true, description: "The Country ID. You will get it from the Countries API", example: "for e.g: Country Id for U.A.E is 235 and that of India is 100", default: "" }
          }

          @example_path = "pattana/api/v1/docs/"
          @examples = ["pos_case_1", "pos_case_2", "pos_case_3", "pos_case_4", "neg_case_1"]

          set_nav("docs/pattana/cities_in_a_country")

          render 'kuppayam/api/docs/show'
        end

        def cities_in_a_region
          set_title("Cities API (in a region)")
          @request_type = "GET"
          @end_point = "/api/v1/regions/:region_id/cities"
          @description = <<-eos
          This API will return all the cities in a particular region. <br>
          The Region ID has to be passed. <br>
          This API can also be used to search cities in a region by passing a query parameter 'q'.
          eos

          @info = "It will return only those cities who has show_in_api set true"
          
          @input_headers = {
            "Content-Type" => { value: "application/json", description: "The MIME media type for JSON text is application/json. This is to make sure that a valid json is returned. The default encoding is UTF-8. " }
          }

          @input_params = {
            country_id: { mandatory: true, description: "The Country ID. You will get it from the Countries API", example: "for e.g: Country Id for U.A.E is 235 and that of India is 100", default: "" },
            region_id: { mandatory: true, description: "The Region ID. You will get it from the Regions API", example: "for e.g: Country Id for India is 100 and Region ID for Kerala is 1314", default: "" }
          }

          @example_path = "pattana/api/v1/docs/"
          @examples = ["pos_case_1", "pos_case_2", "pos_case_3", "pos_case_4", "neg_case_1"]

          set_nav("docs/pattana/cities_in_a_region")

          render 'kuppayam/api/docs/show'
        end

        private

        def set_nav_items
          @nav_items = {
            countries: { nav_class: "docs/pattana/countries", icon_class: "fa-flag-checkered", url: pattana.docs_api_v1_countries_path, text: "Countries API"},
            regions: { nav_class: "docs/pattana/regions", icon_class: "fa-globe", url: pattana.docs_api_v1_regions_path, text: "Countries API"},
            cities_in_a_country: { nav_class: "docs/pattana/cities_in_a_country", icon_class: "fa-map-marker", url: pattana.docs_api_v1_cities_in_a_country_path, text: "Cities (in a Country)"},
            cities_in_a_region: { nav_class: "docs/pattana/cities_in_a_region", icon_class: "fa-map-marker", url: pattana.docs_api_v1_cities_in_a_region_path, text: "Cities (in a Region)"}
          }
        end

        def set_tab_items
          @tab_items = {
            pattana: { nav_class: "docs/pattana", icon_class: "fa-globe", url: pattana.docs_api_v1_countries_path, text: "Location APIs"}
          }
        end

        def breadcrumb_home_path
          pattana.dashboard_path
        end

        def breadcrumbs_configuration
          {
            heading: "Pattana - API Documentation",
            description: "A brief documentation of all APIs implemented in the gem Pattana with input and output details and examples",
            links: []
          }
        end

      end
    end
  end
end

app/controllers/pattana/api/v1/regions_controller.rb
module Pattana
  module Api
    module V1
      class RegionsController < BaseController

        def index
          proc_code = Proc.new do
            @country = Country.find_by_id(params[:country_id])
            if @country
              @relation = @country.regions.includes(:country).show_in_api(true).order("regions.name ASC")
              @relation = @relation.search(params[:q]) if params[:q]
              @relation = @relation.operational(true) if params[:operational] && ["y","t","yes","true",1].include?(params[:operational].downcase)
              @regions = @relation.all
              @data = ActiveModelSerializers::SerializableResource.new(@regions, each_serializer: RegionPreviewSerializer)
              @success = true
            else
              @success = false
              @errors = {
                heading: I18n.translate("api.regions.country_not_found.heading"),
                message: I18n.translate("api.regions.country_not_found.message")
              }
            end
          end
          render_json_response(proc_code)
        end
      end
    end
  end
end

app/controllers/pattana/application_controller.rb
module Pattana
  class ApplicationController < Kuppayam::BaseController

    helper_method :breadcrumb_home_path

    private

    def set_default_title
      set_title("Pattana Admin - Database of Countries, Regions and Cities")
    end

    def configure_filter_param_mapping
      @filter_param_mapping = default_filter_param_mapping
      @filter_param_mapping[:show_in_api] = :show_in_api
      @filter_param_mapping[:operational] = :operational
    end

    def breadcrumb_home_path
      pattana.dashboard_path
    end

  end
end

app/controllers/pattana/cities_controller.rb
module Pattana
  class CitiesController < ResourceController

    def show_in_api
      @city = @r_object = City.find(params[:id])
      if @city
        @city.show_in_api = true
        if @city.valid?
          @city.save
          set_notification(true, I18n.t('cities.show_in_api.heading'), I18n.t('cities.show_in_api.message'))
        else
          set_notification(false, I18n.t('status.error'), I18n.translate("error"), @city.errors.full_messages.join("<br>"))
        end
      else
        set_notification(false, I18n.t('status.error'), I18n.t('status.error', item: default_item_name.titleize))
      end
      render_row
    end

    def hide_in_api
      @city = @r_object = City.find(params[:id])
      if @city
        @city.show_in_api = false
        if @city.valid?
          @city.save
          set_notification(true, I18n.t('cities.hide_in_api.heading'), I18n.t('cities.hide_in_api.message'))
        else
          set_notification(false, I18n.t('status.error'), I18n.translate("error"), @city.errors.full_messages.join("<br>"))
        end
      else
        set_notification(false, I18n.t('status.error'), I18n.t('status.error', item: default_item_name.titleize))
      end
      render_row
    end

    def mark_as_operational
      @city = @r_object = City.find(params[:id])
      if @city
        @city.operational = true
        if @city.valid?
          @city.save
          set_notification(true, I18n.t('cities.marked_as_operational.heading'), I18n.t('cities.marked_as_operational.message'))
        else
          set_notification(false, I18n.t('status.error'), I18n.translate("error"), @city.errors.full_messages.join("<br>"))
        end
      else
        set_notification(false, I18n.t('status.error'), I18n.t('status.error', item: default_item_name.titleize))
      end
      render_row
    end

    def remove_operational
      @city = @r_object = City.find(params[:id])
      if @city
        @city.operational = false
        if @city.valid?
          @city.save
          set_notification(true, I18n.t('cities.removed_operational.heading'), I18n.t('cities.removed_operational.message'))
        else
          set_notification(false, I18n.t('status.error'), I18n.translate("error"), @city.errors.full_messages.join("<br>"))
        end
      else
        set_notification(false, I18n.t('status.error'), I18n.t('status.error', item: default_item_name.titleize))
      end
      render_row
    end

    private

    def get_collections
      @relation = City.includes(:country, :region).where("")

      parse_filters
      apply_filters
      
      @cities = @r_objects = @relation.page(@current_page).per(@per_page)

      return true
    end

    def apply_filters
      @relation = @relation.search(@query) if @query
      @relation = @relation.status(@status) if @status
      
      @order_by = "name ASC" unless @order_by
      @relation = @relation.order(@order_by)
    end

    def configure_filter_settings
      @filter_settings = {
        string_filters: [
          { filter_name: :query },
          { filter_name: :status }
        ],
        boolean_filters: [],
        reference_filters: [],
        variable_filters: [],
      }
    end

    def configure_filter_ui_settings
      @filter_ui_settings = {}
    end

    def resource_controller_configuration
      {
        page_title: "Cities",
        js_view_path: "/kuppayam/workflows/peacock",
        view_path: "/pattana/cities"
      }
    end

    def breadcrumbs_configuration
      {
        heading: "Manage Cities",
        icon: "fa-map-marker",
        description: "Listing all Cities",
        links: [{name: "Home", link: breadcrumb_home_path, icon: 'fa-home'}, 
                  {name: "Manage Cities", link: pattana.cities_path, icon: 'fa-map-marker', active: true}]
      }
    end

    def permitted_params
      params.require(:city).permit(:name, :alternative_names, :iso_code, :population, :latitude, :longitude, :country_id, :region_id)
    end

    def set_navs
      set_nav("admin/cities")
    end

  end
end

app/controllers/pattana/dashboard_controller.rb
module Pattana
  class DashboardController < ApplicationController

  	# GET /dashboard
    def index
    end

    private

    def breadcrumbs_configuration
      {
        heading: "Dashboard - Pattana",
        description: "A Quick view of Countries, Regions & Cities",
        links: [{name: "Dashboard - Pattana", link: breadcrumb_home_path, icon: 'fa-dashboard'}]
      }
    end

    def set_navs
      set_nav("master_data/dashboard")
    end

  end
end

app/helpers/pattana/application_helper.rb
module Pattana
  module ApplicationHelper
  end
end

app/views/pattana/countries/_show.html.erb
<div id="div_country_show">
  
  <div class="row">

    <div class="col-md-3 col-sm-12 col-xs-12" style="border-right:1px solid #f1f1f1;">
      <div class="m-10">
      <%# if display_edit_links? %>
      <%= edit_image(@country, 
          "flag_image.image.large.url",
          upload_image_link(@country, :flag_image, nil ),
          remove_image_link(@country, :flag_image, nil ),
          image_options: {assoc_name: :flag_image}) %>
      <%# else %>
        <%#= display_image(@country, "flag_image.image.large.url", class: "img-inline", alt: @country.display_name) %>
      <%# end %>
      </div>
    </div>

    <div class="col-md-6 col-sm-12 col-xs-12" style="border-right:1px solid #f1f1f1;">
        <%= theme_panel_heading(@country.name) %>
        <%= theme_panel_sub_heading(@country.id, "#") %>
        
        <%= clear_tag(10) %>
        <% if @country.show_in_api? %>
          <div class="label label-success">Show In API</div>
        <% else %>
          <div class="label label-danger">Hide In API</div>
        <% end %>

        <% if @country.operational? %>
          <div class="label label-success">Operational</div>
        <% else %>
          <div class="label label-danger">Non Operational</div>
        <% end %>
        <%= clear_tag(10) %>
    </div>

    <div class="col-md-3 col-sm-12 col-xs-12">

      <% if @country.show_in_api? %>
        <!-- Hide in API -->
        <%= link_to raw("<i class=\"fa fa-cloud mr-5\"></i> Hide in API"), hide_in_api_country_path(:id => @country.id), :remote=>true, class: "btn btn-block btn-danger btn-only-hover" %>
      <% else %>
        <!-- Show in API -->
        <%= link_to raw("<i class=\"fa fa-cloud-download mr-5\"></i> Show in API"), show_in_api_country_path(:id => @country.id), :remote=>true, class: "btn btn-block btn-success btn-only-hover" %>
      <% end %>

      <% if @country.operational? %>
        <!-- Hide in API -->
        <%= link_to raw("<i class=\"fa fa-toggle-off mr-5\"></i> Remove Operational"), remove_operational_country_path(:id => @country.id), :remote=>true, class: "btn btn-block btn-danger btn-only-hover" %>
      <% else %>
        <!-- Show in API -->
        <%= link_to raw("<i class=\"fa fa-toggle-on mr-5\"></i> Mark as Operational"), mark_as_operational_country_path(:id => @country.id), :remote=>true, class: "btn btn-block btn-success btn-only-hover" %>
      <% end %>

      <% edit_link = edit_country_path(id: @country.id) %>
      <% delete_link = country_path(id: @country.id) %>

      <!-- Edit -->
      <%= link_to raw("<i class=\"fa fa-edit mr-5\"></i> Edit"), edit_link, :remote=>true, class: "btn btn-block btn-white btn-only-hover" %>

      <!-- Delete -->
      <%= link_to raw("<i class=\"linecons-trash mr-5\"></i> Delete"), delete_link, method: :delete, :remote=>true, data: { confirm: 'Are you sure?' }, class: "btn btn-block btn-danger btn-only-hover" %>
      
      <div class="visible-sm visible-xs mb-50"></div>
    </div>

  </div>

  <%= clear_tag(50) %>

  <ul class="nav nav-pills">

    <li class="active">
      <a href="#country_details" data-toggle="tab" aria-expanded="false">
        <span class="visible-xs"><i class="fa-database"></i></span>
        <span class="hidden-xs">Country Details</span>
      </a>
    </li>

    <li class="">
      <a href="#regions" data-toggle="tab" aria-expanded="false">
        <span class="visible-xs"><i class="fa-database"></i></span>
        <span class="hidden-xs">Regions</span>
      </a>
    </li>

    <li class="">
      <a href="#cities" data-toggle="tab" aria-expanded="false">
        <span class="visible-xs"><i class="fa-database"></i></span>
        <span class="hidden-xs">Cities</span>
      </a>
    </li>
  </ul>

  <div class="tab-content">

    <div class="tab-pane active" id="country_details" style="border: 1px solid #000;min-height:200px;padding:20px;margin-bottom:20px;max-height: 400px;overflow-y: auto;">
      
      <%= clear_tag(20) %>

      <div class="table-responsive"> 

        <table class="table table-striped table-condensed table-bordered mb-30"> 
          <tbody>
            
            <tr>
              <th style="width:25%;">FIPS</th>
              <th style="width:25%">ISO 2</th>
              <th style="width:25%">ISO 3</th>
              <th style="width:25%">ITU</th>
            </tr>

            <tr>
              <td class="word-break"><%= @country.fips %></td>
              <td class="word-break"><%= @country.iso_alpha_2 %></td>
              <td class="word-break"><%= @country.iso_alpha_3 %></td>
              <td class="word-break"><%= @country.itu_code %></td>
            </tr>

            <tr>
              <th>Dialing Prefix</th>
              <th>Top Level Domain</th>
              <th>Currency Code</th>
              <th>Currency Name</th>
            </tr>

            <tr>
              <td class="word-break"><%= @country.dialing_prefix %></td>
              <td class="word-break"><%= @country.tld %></td>
              <td class="word-break"><%= @country.currency_code %></td>
              <td class="word-break"><%= @country.currency_name %></td>
            </tr>

            <tr>
              <th>Is Independent?</th>
              <th>Languages</th>
              <th>Capital</th>
              <th>Continent</th>
            </tr>

            <tr>
              <td class="word-break"><%= @country.is_independent %></td>
              <td class="word-break"><%= @country.languages %></td>
              <td class="word-break"><%= @country.capital %></td>
              <td class="word-break"><%= @country.continent %></td>
            </tr>

            <tr>
              <th>Show in API</th>
              <th>Priority</th>
              <th>Latitude</th>
              <th>Longitude</th>
            </tr>

            <tr>
              <td class="word-break"><%= @country.show_in_api %></td>
              <td class="word-break"><%= @country.priority %></td>
              <td class="word-break"><%= @country.latitude %></td>
              <td class="word-break"><%= @country.longitude %></td>
            </tr>

            <tr>
              <th>Latitude</th>
              <th>Longitude</th>
              <th>Created At</th>
              <th>Updated At</th>
            </tr>

            <tr>
              <td class="word-break"><%= @country.latitude %></td>
              <td class="word-break"><%= @country.longitude %></td>
              <td class="word-break"><%= @country.created_at %></td>
              <td class="word-break"><%= @country.updated_at %></td>
            </tr>

          </tbody>
        </table>
      </div>
    </div>

    <div class="tab-pane" id="regions" style="border: 1px solid #000;min-height:200px;padding:20px;margin-bottom:20px;max-height: 400px;overflow-y: auto;">
      <%= clear_tag(20) %>

      <div id="div_region_counts">
        <div class="row">

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
          
            <div style="border: 1px solid #ddd; margin-bottom: 20px;">
            
              <div class="xe-widget xe-counter xe-counter-info" 
                  data-count=".num" 
                  data-from="0" 
                  data-to="99.9" 
                  data-suffix="%" 
                  data-duration="2"
                  style="margin-bottom: 0px; 
                  padding: 0px; 
                  width: 15%;
                  margin: 0px auto;">
                <div class="xe-icon">
                  <i class="linecons-database"></i>
                </div>
                <div class="xe-label">
                  <strong class="num"><%= @country.regions.count %></strong>
                  <span>Total</span>
                </div>
              </div>

            </div>
          </div>

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
          
            <div style="border: 1px solid #ddd; margin-bottom: 20px;">
            
              <div class="xe-widget xe-counter" 
                  data-count=".num" 
                  data-from="0" 
                  data-to="99.9" 
                  data-suffix="%" 
                  data-duration="2"
                  style="margin-bottom: 0px; 
                  padding: 0px; 
                  width: 15%;
                  margin: 0px auto;">
                <div class="xe-icon">
                  <i class="linecons-cloud"></i>
                </div>
                <div class="xe-label">
                  <strong class="num"><%= @country.regions.show_in_api(true).count %></strong>
                  <span>Show in API</span>
                </div>
              </div>

            </div>
          </div>

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
          
            <div style="border: 1px solid #ddd; margin-bottom: 20px;">
            
              <div class="xe-widget xe-counter" 
                  data-count=".num" 
                  data-from="0" 
                  data-to="99.9" 
                  data-suffix="%" 
                  data-duration="2"
                  style="margin-bottom: 0px; 
                  padding: 0px; 
                  width: 15%;
                  margin: 0px auto;">
                <div class="xe-icon">
                  <i class="fa-toggle-on"></i>
                </div>
                <div class="xe-label">
                  <strong class="num"><%= @country.regions.operational(true).count %></strong>
                  <span>Operational</span>
                </div>
              </div>

            </div>
          </div>
          
        </div>
      </div>

      <div id="div_region_action_buttons">
      </div>

      <div id="div_region_index">
        <div class="text-center">
          <p>Click the below button to see the list of regions in <%= @country.name %></p>
          <%= link_to('Show Regions', regions_country_path(@country), class: "mt-10 btn btn-success", remote: true) %>
        </div>
      </div>
    </div>

    <div class="tab-pane" id="cities" style="border: 1px solid #000;min-height:200px;padding:20px;margin-bottom:20px;max-height: 400px;overflow-y: auto;">
      <%= clear_tag(20) %>

      <div id="div_city_counts">
        <div class="row">

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
          
            <div style="border: 1px solid #ddd; margin-bottom: 20px;">
            
              <div class="xe-widget xe-counter xe-counter-info" 
                  data-count=".num" 
                  data-from="0" 
                  data-to="99.9" 
                  data-suffix="%" 
                  data-duration="2"
                  style="margin-bottom: 0px; 
                  padding: 0px; 
                  width: 15%;
                  margin: 0px auto;">
                <div class="xe-icon">
                  <i class="linecons-database"></i>
                </div>
                <div class="xe-label">
                  <strong class="num"><%= @country.cities.count %></strong>
                  <span>Total</span>
                </div>
              </div>

            </div>

          </div>

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
          
            <div style="border: 1px solid #ddd; margin-bottom: 20px;">
            
              <div class="xe-widget xe-counter" 
                  data-count=".num" 
                  data-from="0" 
                  data-to="99.9" 
                  data-suffix="%" 
                  data-duration="2"
                  style="margin-bottom: 0px; 
                  padding: 0px; 
                  width: 15%;
                  margin: 0px auto;">
                <div class="xe-icon">
                  <i class="linecons-cloud"></i>
                </div>
                <div class="xe-label">
                  <strong class="num"><%= @country.cities.show_in_api(true).count %></strong>
                  <span>Show in API</span>
                </div>
              </div>

            </div>

          </div>

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
          
            <div style="border: 1px solid #ddd; margin-bottom: 20px;">
            
              <div class="xe-widget xe-counter" 
                  data-count=".num" 
                  data-from="0" 
                  data-to="99.9" 
                  data-suffix="%" 
                  data-duration="2"
                  style="margin-bottom: 0px; 
                  padding: 0px; 
                  width: 15%;
                  margin: 0px auto;">
                <div class="xe-icon">
                  <i class="fa-toggle-on"></i>
                </div>
                <div class="xe-label">
                  <strong class="num"><%= @country.cities.operational(true).count %></strong>
                  <span>Operational</span>
                </div>
              </div>

            </div>

          </div>
          
          
        </div>
      </div>

      <div id="div_city_action_buttons">
      </div>

      <div id="div_city_index">
        <div class="text-center">
          <p>Click the below button to see the list of cities in <%= @country.name %></p>
          <%= link_to('Show Cities', cities_country_path(@country), class: "mt-10 btn btn-success", remote: true) %>
        </div>
      </div>
    </div>

  </div>

  <%= link_to "Close", "#", onclick: "closeLargeModal();", class: "btn btn-primary pull-right" %>

  <% edit_link = edit_country_path(id: @country.id) %>
  <%= link_to raw("<i class='fa fa-pencil mr-5'></i><span>Edit</span>"), edit_link, remote: true, class: "pull-right mr-10 btn btn-white" %>

  <%= clear_tag %>
</div>