config/routes.rb
Pattana::Engine.routes.draw do

  get 'dashboard/pattana',  to: "dashboard#index",  as: :dashboard

  scope :admin do
    resources :countries,  as: :countries do
      member do
        get :regions
        get :cities
        get :show_in_api
        get :hide_in_api
        get :mark_as_operational
        get :remove_operational
      end
    end

    resources :regions,  as: :regions do
      member do
        get :cities
        get :show_in_api
        get :hide_in_api
        get :mark_as_operational
        get :remove_operational
      end
    end

    resources :cities,  as: :cities do
      member do
        get :show_in_api
        get :hide_in_api
        get :mark_as_operational
        get :remove_operational
      end
    end
  end

  namespace :api do
    namespace :v1 do
      get 'countries', :controller => "countries", action: :index, as: :countries
      get ':country_id/regions', :controller => "regions", action: :index, as: :regions
      get 'countries/:country_id/cities', :controller => "cities", action: :cities_in_a_country, as: :cities_in_a_country
      get 'regions/:region_id/cities', :controller => "cities", action: :cities_in_a_region, as: :cities_in_a_region
    end
  end
  
  scope :docs, as: 'docs' do
    namespace :api do
      namespace :v1 do
        get 'countries', :controller => "docs"
        get 'regions', :controller => "docs"
        get 'cities_in_a_country', :controller => "docs"
        get 'cities_in_a_region', :controller => "docs"
      end
    end
  end

end

app/controllers/pattana/api/v1/base_controller.rb
module Pattana
  module Api
    module V1
      class BaseController < ActionController::API

        include ActionController::HttpAuthentication::Token::ControllerMethods
        include RenderApiHelper

      end
    end
  end
end

app/controllers/pattana/api/v1/cities_controller.rb
module Pattana
  module Api
    module V1
      class CitiesController < BaseController

        def cities_in_a_country
          proc_code = Proc.new do
            @country = Country.find_by_id(params[:country_id])
            if @country
              @relation = @country.cities.includes(:region, :country).show_in_api(true).order("cities.name ASC")
              @relation = @relation.search(params[:q]) if params[:q]
              @relation = @relation.operational(true) if params[:operational] && ["y","t","yes","true",1].include?(params[:operational].downcase)
              @cities = @relation.all
              @data = ActiveModelSerializers::SerializableResource.new(@cities, each_serializer: CityPreviewSerializer)
              @success = true
            else
              @success = false
              @errors = {
                heading: I18n.translate("api.cities.country_not_found.heading"),
                message: I18n.translate("api.cities.country_not_found.message")
              }
            end
          end
          render_json_response(proc_code)
        end

        def cities_in_a_region
          proc_code = Proc.new do
            @region = Region.find_by_id(params[:region_id])
            if @region
              @relation = @region.cities.includes(:region, :country).show_in_api(true).order("cities.name ASC")
              @relation = @relation.search(params[:q]) if params[:q]
              @relation = @relation.operational(true) if params[:operational] && ["y","t","yes","true",1].include?(params[:operational].downcase)
              @cities = @relation.all
              @data = ActiveModelSerializers::SerializableResource.new(@cities, each_serializer: CityPreviewSerializer)
              @success = true
            else
              @success = false
              @errors = {
                heading: I18n.translate("api.cities.region_not_found.heading"),
                message: I18n.translate("api.cities.region_not_found.message")
              }
            end
          end
          render_json_response(proc_code)
        end
      end
    end
  end
end

app/controllers/pattana/api/v1/countries_controller.rb
module Pattana
  module Api
    module V1
      class CountriesController < BaseController

        def index
          proc_code = Proc.new do
            @relation = Country.show_in_api(true).order("countries.name ASC")
            @relation = @relation.search(params[:q]) if params[:q]
            @relation = @relation.operational(true) if params[:operational] && ["y","t","yes","true",1].include?(params[:operational].downcase)
            @countries = @relation.all
            @data = ActiveModelSerializers::SerializableResource.new(@countries, each_serializer: CountryPreviewSerializer)
            @success = true
          end
          render_json_response(proc_code)
        end

        
        
      end
    end
  end
end

app/controllers/pattana/api/v1/docs_controller.rb
module Pattana
  module Api
    module V1
      class DocsController < Pattana::ApplicationController

        layout 'kuppayam/docs'

        before_action :set_nav_items, :set_tab_items
        helper_method :breadcrumb_home_path

        def countries
          set_title("Countries API")
          @request_type = "GET"
          @end_point = "/api/v1/countries"
          @description = <<-eos
          This API will return all the countries with other details like dialing prefix and ISO codes. <br>
          This API can also be used to search countries by passing a query parameter 'q'.<br>
          eos

          @info = "It will return only those countries who has show_in_api set true"

          @input_headers = {
            "Content-Type" => { value: "application/json", description: "The MIME media type for JSON text is application/json. This is to make sure that a valid json is returned. The default encoding is UTF-8. " }
          }

          @example_path = "pattana/api/v1/docs/"
          @examples = ["pos_case_1", "pos_case_2", "pos_case_3", "pos_case_4"]

          set_nav("docs/pattana/countries")

          render 'kuppayam/api/docs/show'
        end

        def regions
          set_title("Regions API")
          @request_type = "GET"
          @end_point = "/api/v1/:country_id/regions"
          @description = <<-eos
          This API will return all the regions in a particular country. <br>
          The Country ID has to be passed. <br>
          This API can also be used to search regions by passing a query parameter 'q'.
          eos

          @info = "It will return only those regions who has show_in_api set true"

          @input_headers = {
            "Content-Type" => { value: "application/json", description: "The MIME media type for JSON text is application/json. This is to make sure that a valid json is returned. The default encoding is UTF-8. " }
          }

          @input_params = {
            country_id: { mandatory: true, description: "The Country ID. You will get it from the Countries API", example: "for e.g: Country Id for U.A.E is 235 and that of India is 100", default: "" }
          }

          @example_path = "pattana/api/v1/docs/"
          @examples = ["pos_case_1", "pos_case_2", "pos_case_3", "pos_case_4", "neg_case_1"]

          set_nav("docs/pattana/regions")

          render 'kuppayam/api/docs/show'
        end

        def cities_in_a_country
          set_title("Cities API (in a country)")
          @request_type = "GET"
          @end_point = "/api/v1/countries/:country_id/cities"
          @description = ""
          @description = <<-eos
          This API will return all the cities in a particular country. <br>
          The Country ID has to be passed. <br>
          This API can also be used to search cities in a country by passing a query parameter 'q'.
          eos

          @info = "It will return only those cities who has show_in_api set true"

          @input_headers = {
            "Content-Type" => { value: "application/json", description: "The MIME media type for JSON text is application/json. This is to make sure that a valid json is returned. The default encoding is UTF-8. " }
          }

          @input_params = {
            country_id: { mandatory: true, description: "The Country ID. You will get it from the Countries API", example: "for e.g: Country Id for U.A.E is 235 and that of India is 100", default: "" }
          }

          @example_path = "pattana/api/v1/docs/"
          @examples = ["pos_case_1", "pos_case_2", "pos_case_3", "pos_case_4", "neg_case_1"]

          set_nav("docs/pattana/cities_in_a_country")

          render 'kuppayam/api/docs/show'
        end

        def cities_in_a_region
          set_title("Cities API (in a region)")
          @request_type = "GET"
          @end_point = "/api/v1/regions/:region_id/cities"
          @description = <<-eos
          This API will return all the cities in a particular region. <br>
          The Region ID has to be passed. <br>
          This API can also be used to search cities in a region by passing a query parameter 'q'.
          eos

          @info = "It will return only those cities who has show_in_api set true"
          
          @input_headers = {
            "Content-Type" => { value: "application/json", description: "The MIME media type for JSON text is application/json. This is to make sure that a valid json is returned. The default encoding is UTF-8. " }
          }

          @input_params = {
            country_id: { mandatory: true, description: "The Country ID. You will get it from the Countries API", example: "for e.g: Country Id for U.A.E is 235 and that of India is 100", default: "" },
            region_id: { mandatory: true, description: "The Region ID. You will get it from the Regions API", example: "for e.g: Country Id for India is 100 and Region ID for Kerala is 1314", default: "" }
          }

          @example_path = "pattana/api/v1/docs/"
          @examples = ["pos_case_1", "pos_case_2", "pos_case_3", "pos_case_4", "neg_case_1"]

          set_nav("docs/pattana/cities_in_a_region")

          render 'kuppayam/api/docs/show'
        end

        private

        def set_nav_items
          @nav_items = {
            countries: { nav_class: "docs/pattana/countries", icon_class: "fa-flag-checkered", url: pattana.docs_api_v1_countries_path, text: "Countries API"},
            regions: { nav_class: "docs/pattana/regions", icon_class: "fa-globe", url: pattana.docs_api_v1_regions_path, text: "Countries API"},
            cities_in_a_country: { nav_class: "docs/pattana/cities_in_a_country", icon_class: "fa-map-marker", url: pattana.docs_api_v1_cities_in_a_country_path, text: "Cities (in a Country)"},
            cities_in_a_region: { nav_class: "docs/pattana/cities_in_a_region", icon_class: "fa-map-marker", url: pattana.docs_api_v1_cities_in_a_region_path, text: "Cities (in a Region)"}
          }
        end

        def set_tab_items
          @tab_items = {
            pattana: { nav_class: "docs/pattana", icon_class: "fa-globe", url: pattana.docs_api_v1_countries_path, text: "Location APIs"}
          }
        end

        def breadcrumb_home_path
          pattana.dashboard_path
        end

        def breadcrumbs_configuration
          {
            heading: "Pattana - API Documentation",
            description: "A brief documentation of all APIs implemented in the gem Pattana with input and output details and examples",
            links: []
          }
        end

      end
    end
  end
end

app/controllers/pattana/api/v1/regions_controller.rb
module Pattana
  module Api
    module V1
      class RegionsController < BaseController

        def index
          proc_code = Proc.new do
            @country = Country.find_by_id(params[:country_id])
            if @country
              @relation = @country.regions.includes(:country).show_in_api(true).order("regions.name ASC")
              @relation = @relation.search(params[:q]) if params[:q]
              @relation = @relation.operational(true) if params[:operational] && ["y","t","yes","true",1].include?(params[:operational].downcase)
              @regions = @relation.all
              @data = ActiveModelSerializers::SerializableResource.new(@regions, each_serializer: RegionPreviewSerializer)
              @success = true
            else
              @success = false
              @errors = {
                heading: I18n.translate("api.regions.country_not_found.heading"),
                message: I18n.translate("api.regions.country_not_found.message")
              }
            end
          end
          render_json_response(proc_code)
        end
      end
    end
  end
end

app/controllers/pattana/application_controller.rb
module Pattana
  class ApplicationController < Kuppayam::BaseController

    helper_method :breadcrumb_home_path

    private

    def set_default_title
      set_title("Pattana Admin - Database of Countries, Regions and Cities")
    end

    def configure_filter_param_mapping
      @filter_param_mapping = default_filter_param_mapping
      @filter_param_mapping[:show_in_api] = :show_in_api
      @filter_param_mapping[:operational] = :operational
    end

    def breadcrumb_home_path
      pattana.dashboard_path
    end

  end
end

app/controllers/pattana/cities_controller.rb
module Pattana
  class CitiesController < ResourceController

    def show_in_api
      @city = @r_object = City.find(params[:id])
      if @city
        @city.show_in_api = true
        if @city.valid?
          @city.save
          set_notification(true, I18n.t('cities.show_in_api.heading'), I18n.t('cities.show_in_api.message'))
        else
          set_notification(false, I18n.t('status.error'), I18n.translate("error"), @city.errors.full_messages.join("<br>"))
        end
      else
        set_notification(false, I18n.t('status.error'), I18n.t('status.error', item: default_item_name.titleize))
      end
      render_row
    end

    def hide_in_api
      @city = @r_object = City.find(params[:id])
      if @city
        @city.show_in_api = false
        if @city.valid?
          @city.save
          set_notification(true, I18n.t('cities.hide_in_api.heading'), I18n.t('cities.hide_in_api.message'))
        else
          set_notification(false, I18n.t('status.error'), I18n.translate("error"), @city.errors.full_messages.join("<br>"))
        end
      else
        set_notification(false, I18n.t('status.error'), I18n.t('status.error', item: default_item_name.titleize))
      end
      render_row
    end

    def mark_as_operational
      @city = @r_object = City.find(params[:id])
      if @city
        @city.operational = true
        if @city.valid?
          @city.save
          set_notification(true, I18n.t('cities.marked_as_operational.heading'), I18n.t('cities.marked_as_operational.message'))
        else
          set_notification(false, I18n.t('status.error'), I18n.translate("error"), @city.errors.full_messages.join("<br>"))
        end
      else
        set_notification(false, I18n.t('status.error'), I18n.t('status.error', item: default_item_name.titleize))
      end
      render_row
    end

    def remove_operational
      @city = @r_object = City.find(params[:id])
      if @city
        @city.operational = false
        if @city.valid?
          @city.save
          set_notification(true, I18n.t('cities.removed_operational.heading'), I18n.t('cities.removed_operational.message'))
        else
          set_notification(false, I18n.t('status.error'), I18n.translate("error"), @city.errors.full_messages.join("<br>"))
        end
      else
        set_notification(false, I18n.t('status.error'), I18n.t('status.error', item: default_item_name.titleize))
      end
      render_row
    end

    private

    def get_collections
      @relation = City.includes(:country, :region).where("")

      parse_filters
      apply_filters
      
      @cities = @r_objects = @relation.page(@current_page).per(@per_page)

      return true
    end

    def apply_filters
      @relation = @relation.search(@query) if @query
      @relation = @relation.status(@status) if @status
      
      @order_by = "name ASC" unless @order_by
      @relation = @relation.order(@order_by)
    end

    def configure_filter_settings
      @filter_settings = {
        string_filters: [
          { filter_name: :query },
          { filter_name: :status }
        ],
        boolean_filters: [],
        reference_filters: [],
        variable_filters: [],
      }
    end

    def configure_filter_ui_settings
      @filter_ui_settings = {}
    end

    def resource_controller_configuration
      {
        page_title: "Cities",
        js_view_path: "/kuppayam/workflows/peacock",
        view_path: "/pattana/cities"
      }
    end

    def breadcrumbs_configuration
      {
        heading: "Manage Cities",
        icon: "fa-map-marker",
        description: "Listing all Cities",
        links: [{name: "Home", link: breadcrumb_home_path, icon: 'fa-home'}, 
                  {name: "Manage Cities", link: pattana.cities_path, icon: 'fa-map-marker', active: true}]
      }
    end

    def permitted_params
      params.require(:city).permit(:name, :alternative_names, :iso_code, :population, :latitude, :longitude, :country_id, :region_id)
    end

    def set_navs
      set_nav("admin/cities")
    end

  end
end

app/controllers/pattana/dashboard_controller.rb
module Pattana
  class DashboardController < ApplicationController

  	# GET /dashboard
    def index
    end

    private

    def breadcrumbs_configuration
      {
        heading: "Dashboard - Pattana",
        description: "A Quick view of Countries, Regions & Cities",
        links: [{name: "Dashboard - Pattana", link: breadcrumb_home_path, icon: 'fa-dashboard'}]
      }
    end

    def set_navs
      set_nav("master_data/dashboard")
    end

  end
end

app/helpers/pattana/application_helper.rb
module Pattana
  module ApplicationHelper
  end
end

app/views/pattana/region_cities/_action_buttons.html.erb
<div class="row">
  <div class="col-md-6">
    <%= theme_button('Refresh', 'refresh', cities_region_path(@region), classes: "pull-left mr-10", btn_type: "success") %>
    
    <% @filter_ui_settings.each do |filter_name, options| %>
        <% if options[:object_filter] == true %>
          <%= report_object_filter(filter_name, options) %>
        <% else %>
          <%= report_filter(filter_name, options) %>
        <% end %>
      <% end %>
  </div>
  <div class="col-md-6">
    <%= search_form_kuppayam(City, cities_region_path(@region), text: @query) %>
  </div>
</div>
<%= clear_tag(10) %>

app/views/pattana/region_cities/_index.html.erb
<div class="table-responsive"> 
	<table class="table table-hover members-table middle-align">
	  <thead>
			<tr>
				<th style="text-align:center;width:5%;">#</th> 
				<th style="text-align:left;width:35%;">Name</th>
				<th style="text-align:center;width:15%;">ISO Code</th>
				<th style="text-align:center;width:15%;">Priority</th>
				<th style="text-align:center;width:15%;">Show in API</th>
				<th style="text-align:center;width:15%;">Operational</th>
				<th style="text-align:center;" colspan="2">Actions</th>
			</tr>  
		</thead>
		
	  <tbody>
	  	<% @cities.each_with_index do |city, i| %>
	  		
	  		<% edit_link = edit_city_path(id: city.id) %>
				<% delete_link = city_path(id: city.id) %>
				
	  		<tr id="tr_city_<%= city.id %>">
		      
		      <th scope="row" class="text-align-center">
						<% if i < 0 %>
							<i class="fa fa-check text-success"></i>
						<% else %>
							<%= i + 1 + (@per_page.to_i * (@current_page.to_i - 1)) %>
						<% end %>
					</th>

					<td class="text-align-left"><%= city.display_name %></td>
		      <td class="text-align-center"><%= city.iso_code %></td>
		      <td class="text-align-center"><%= city.priority %></td>
		      <td class="text-align-center"><%= city.display_show_in_api %></td>

		      <td class="action-links text-align-center" style="width:10%">
				    <% if city.show_in_api? %>
				      <%= link_to raw("<i class=\"fa fa-square mr-5\"></i> Hide in API"), hide_in_api_city_path(:id =>city.id), :remote=>true, role: "menuitem", tabindex: "-1", style: "text-align:left;", class: "delete" %>
				    <% else %>
				      <%= link_to raw("<i class=\"fa fa-square mr-5\"></i> Show in API"), show_in_api_city_path(:id =>city.id), :remote=>true, role: "menuitem", tabindex: "-1", style: "text-align:left;", class: "edit" %>
				    <% end %>

				    <% if city.operational? %>
				      <%= link_to raw("<i class=\"fa fa-square mr-5\"></i> Remove Operational"), remove_operational_city_path(:id =>city.id), :remote=>true, role: "menuitem", tabindex: "-1", style: "text-align:left;", class: "delete" %>
				    <% else %>
				      <%= link_to raw("<i class=\"fa fa-square mr-5\"></i> Mark as Operational"), mark_as_operational_city_path(:id =>city.id), :remote=>true, role: "menuitem", tabindex: "-1", style: "text-align:left;", class: "edit" %>
				    <% end %>
				  </td>

				  <td class="action-links text-align-center" style="width:10%">
				    <%= link_to raw("<i class=\"linecons-pencil\"></i> Edit City"), edit_link, :remote=>true, class: "edit" %>

				    <%= link_to raw("<i class=\"linecons-trash\"></i> Delete"), delete_link, method: :delete, role: "menuitem", tabindex: "-1", data: { confirm: 'Are you sure?' }, :remote=>true, class: "delete" %>
				  </td>

		    </tr>
		  <% end %>
	  </tbody>
	</table>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= paginate_kuppayam(@cities) %>
  </div>
</div>

app/views/pattana/region_cities/_row.html.erb
<% edit_link = edit_city_path(id: city.id) %>
<% delete_link = city_path(id: city.id) %>

<tr id="tr_city_<%= city.id %>">
          
  <th scope="row" style="text-align:center;width:5%;">
    <% if i < 0 %>
      <i class="fa fa-check text-success"></i>
    <% else %>
      <%= i + 1 + (@per_page.to_i * (@current_page.to_i - 1)) %>
    <% end %>
  </th>

  <td class="city-name" style="text-align:center;width:50%;"><%= city.display_name %></td>

  <td class="city-name" style="text-align:center;width:15%;"><%= city.iso_code %></td>

  <td class="city-name" style="text-align:center;width:15%;"><%= city.priority %></td>

  <td class="city-name" style="text-align:center;width:15%;"><%= city.display_show_in_api %></td>

  <td class="action-links text-align-center" style="width:10%">
    <% if city.show_in_api? %>
      <%= link_to raw("<i class=\"fa fa-square mr-5\"></i> Hide in API"), hide_in_api_city_path(:id =>city.id), :remote=>true, role: "menuitem", tabindex: "-1", style: "text-align:left;", class: "delete" %>
    <% else %>
      <%= link_to raw("<i class=\"fa fa-square mr-5\"></i> Show in API"), show_in_api_city_path(:id =>city.id), :remote=>true, role: "menuitem", tabindex: "-1", style: "text-align:left;", class: "edit" %>
    <% end %>

    <% if city.operational? %>
      <%= link_to raw("<i class=\"fa fa-square mr-5\"></i> Remove Operational"), remove_operational_city_path(:id =>city.id), :remote=>true, role: "menuitem", tabindex: "-1", style: "text-align:left;", class: "delete" %>
    <% else %>
      <%= link_to raw("<i class=\"fa fa-square mr-5\"></i> Mark as Operational"), mark_as_operational_city_path(:id =>city.id), :remote=>true, role: "menuitem", tabindex: "-1", style: "text-align:left;", class: "edit" %>
    <% end %>
  </td>

  <td class="action-links text-align-center" style="width:10%">
    <%= link_to raw("<i class=\"linecons-pencil\"></i> Edit City"), edit_link, :remote=>true, class: "edit" %>

    <%= link_to raw("<i class=\"linecons-trash\"></i> Delete"), delete_link, method: :delete, role: "menuitem", tabindex: "-1", data: { confirm: 'Are you sure?' }, :remote=>true, class: "delete" %>
  </td>

</tr>